dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake

# install:
#   - pip install --user conan cmake

script:
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++9
  - cmake .
  - cmake --build . -- -j2
