language: cpp
sudo: true

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - build-essential
            - cmake

    - os: linux
      dist: bionic
      compiler: clang

    - os: osx
      osx_image: xcode11.3

# - os: windows

# install:
#   - pip install --user conan cmake

script:
  - cmake .
  - cmake --build . -- -j2
