image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Debug
- Release

environment:
  matrix:
  - DBUILD_SHARED_LIBS: 0
  - DBUILD_SHARED_LIBS: 1

before_build:
- cmd: cmake -H. -B./build -DBUILD_SHARED_LIBS=%DBUILD_SHARED_LIBS%

build:
  verbosity: normal